package main

/*
重要说明：本文件由gdi自动生成，请勿手动修改，当被注册的结构体发生变化编译出错时，请删除本文件或清除所有文件内容，只需要保留本包声明即可。
Important note: This file is automatically generated by gdi, do not modify it manually.
If the registered structure changes and the compilation fails, please delete this file or clear all the contents of the file.
Only the package declaration is required.(Note:
In the case of no generated code, the first run of the program will report an error, can not find the package declaration,
need to do a secondary compilation)
*/
import (
	"embed"
	p1 "gdi_aop/controller"
	p2 "gdi_aop/dto"
	"github.com/sjqzhang/gdi"
)

//go:embed controller dto middleware
var gdiEmbedFiles embed.FS

func init() {
	gdi.SetEmbedFs(&gdiEmbedFiles)
	_ = gdi.GDIPool{}
	gdi.PlaceHolder((*p1.HelloController)(nil))
	gdi.PlaceHolder((*p2.HelloRequest)(nil))
}
